{% set name = "azureml_mlflow" %}
{% set version = "1.55.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-py3-none-any.whl
  sha256: 048cd60c483d778b1f52fc219a32c925706dceac871d829946099609959c0eef

build:
  number: 0
  # skipping because of missing mlflow-skinny for s390x
  skip: True  # [s390x]

requirements:
  host:
    # patch tools are in host section since they are necessary only during execution of build script
    - patch     # [not win]
    - m2-patch  # [win]
    - python
    - pip
    - wheel
  run:
    - python
    - six
    - cryptography
    - mlflow-skinny
    - azure-identity
    - azure-common
    - azure-core >=1.8.0,<2.0.0,!=1.22.0
    - azure-mgmt-core >=1.2.0,<2.0.0
    - azure-storage-blob >=12.5.0,<=12.19.0
    - python-dateutil >=2.7.3,<3.0.0
    - msrest >=0.6.18

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - azureml
    - azureml.mlflow
    - azure.core
    - azure.mgmt.core
    - azure.storage.blob
    - mlflow

about:
  home: https://pypi.org/project/azureml-mlflow
  license: MOSA
  license_family: Other
  license_file: azureml_mlflow-1.55.0.dist-info/LICENSE.txt
  summary: Azure Machine Learning SDK allows to build and run machine learning workflows with Azure Machine Learning
           services.
  description: |
    Key areas of the SDK include:
    * Explore, prepare and manage the lifecycle of your datasets used in machine learning experiments.
    * Manage cloud resources for monitoring, logging, and organizing your machine learning experiments.
    * Train models either locally or by using cloud resources, including GPU-accelerated model training.
    * Use automated machine learning, which accepts configuration parameters and training data. It automatically
      iterates through algorithms and hyperparameter settings to find the best model for running predictions.
    * Deploy web services to convert your trained models into RESTful services that can be consumed in any application.
  doc_url: https://learn.microsoft.com/en-us/python/api/overview/azure/ml/?view=azure-ml-py
  dev_url: https://pypi.org/project/azureml-mlflow

extra:
  recipe-maintainers:
    - boldorider4
