{% set name = "azureml_mlflow" %}
{% set version = "1.55.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-py3-none-any.whl

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - azureml-mlflow

about:
  home: https://pypi.org/project/azureml-mlflow
  license: Microsoft Online Subscription Agreement
  license_family: Other
  license_file: LICENSE
  summary: Azure Machine Learning SDK allows to build and run machine learning workflows with Azure Machine Learning
           services.
  description: |
    Key areas of the SDK include:
    * Explore, prepare and manage the lifecycle of your datasets used in machine learning experiments.
    * Manage cloud resources for monitoring, logging, and organizing your machine learning experiments.
    * Train models either locally or by using cloud resources, including GPU-accelerated model training.
    * Use automated machine learning, which accepts configuration parameters and training data. It automatically
      iterates through algorithms and hyperparameter settings to find the best model for running predictions.
    * Deploy web services to convert your trained models into RESTful services that can be consumed in any application.
  doc_url: https://learn.microsoft.com/en-us/python/api/overview/azure/ml/?view=azure-ml-py
  dev_url: https://pypi.org/project/azureml-mlflow

extra:
  recipe-maintainers:
    - ericdill
    - mariusvniekerk
    - croth1
    - ocefpaf
    - jjhelmus
